"""init tables

Revision ID: 25f3b4ecc637
Revises: 
Create Date: 2026-03-06 21:38:28.971606
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '25f3b4ecc637'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('business_impact', sa.Text(), nullable=True),
    sa.Column('requester', sa.String(length=100), nullable=False),
    sa.Column('module', sa.String(length=100), nullable=True),
    sa.Column('priority', sa.Enum('critical', 'high', 'medium', 'low', name='priority_enum'), nullable=False),
    sa.Column('status', sa.Enum('new', 'triage', 'approved', 'rejected', 'postponed', name='status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_created_at', 'requests', ['created_at'], unique=False)
    op.create_index('idx_priority', 'requests', ['priority'], unique=False)
    op.create_index('idx_status', 'requests', ['status'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('kanban_cards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('assignee', sa.String(length=100), nullable=True),
    sa.Column('stage', sa.Enum('todo', 'in_progress', 'review', 'done', name='stage_enum'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    op.create_index('idx_position', 'kanban_cards', ['stage', 'position'], unique=False)
    op.create_index('idx_team_stage', 'kanban_cards', ['team_id', 'stage'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_team_stage', table_name='kanban_cards')
    op.drop_index('idx_position', table_name='kanban_cards')
    op.drop_table('kanban_cards')
    op.drop_table('teams')
    op.drop_index('idx_status', table_name='requests')
    op.drop_index('idx_priority', table_name='requests')
    op.drop_index('idx_created_at', table_name='requests')
    op.drop_table('requests')
    # ### end Alembic commands ###
