"""add start_date due_date to requests

Revision ID: 5cf9022c7901
Revises: 25f3b4ecc637
Create Date: 2026-03-06 22:25:21.765640
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5cf9022c7901'
down_revision: Union[str, None] = '25f3b4ecc637'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('requests', sa.Column('due_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'due_date')
    op.drop_column('requests', 'start_date')
    # ### end Alembic commands ###
