"""add risk, release_date, release_status to requests

Revision ID: 956d358fd574
Revises: d4e5f6a7b8c9
Create Date: 2026-03-09 05:38:05.032926
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '956d358fd574'
down_revision: Union[str, None] = 'd4e5f6a7b8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('risk', sa.Enum('high', 'medium', 'low', name='risk_enum'), nullable=True))
    op.add_column('requests', sa.Column('release_date', sa.Date(), nullable=True))
    op.add_column('requests', sa.Column('release_status', sa.Enum('pending', 'released', 'rollback', name='release_status_enum'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'release_status')
    op.drop_column('requests', 'release_date')
    op.drop_column('requests', 'risk')
    # ### end Alembic commands ###
